name: flutter_otel_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/flutter_otel_api
  - packages/flutter_otel_sdk
  - packages/flutter_otel_exporter_otlp_http
  - packages/flutter_otel
  - packages/flutter_otel_instrumentation_dio
  - packages/flutter_otel_native
